apiVersion: skaffold/v2alpha3
kind: Config
deploy: 
  kubectl: 
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: bold-streamer-296615
  artifacts:
    - image: us.gcr.io/bold-streamer-296615/auth
      context: auth  
      docker: 
        dockerfile: Dockerfile 
      sync: 
        manual:
          - src: 'src/**/*.ts'
            dest: . 